[graph]
all-features = true
no-default-features = false

[advisories]
version = 2
ignore = [
    "RUSTSEC-2024-0436", #paste
]

[bans]
multiple-versions = "warn"
wildcards = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "Unlicense",
]
confidence-threshold = 1.0
private = { ignore = true }
